-- Create internships table
CREATE TABLE IF NOT EXISTS internships (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT,
    responsibilities TEXT,
    benefits TEXT,
    location VARCHAR(255),
    is_remote BOOLEAN DEFAULT FALSE,
    is_hybrid BOOLEAN DEFAULT FALSE,
    type ENUM('full-time', 'part-time', 'contract') DEFAULT 'full-time',
    duration_months INT,
    stipend DECIMAL(10,2),
    stipend_currency VARCHAR(3) DEFAULT 'USD',
    application_deadline DATE,
    start_date DATE,
    end_date DATE,
    status ENUM('draft', 'active', 'closed', 'archived') DEFAULT 'draft',
    views_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    INDEX idx_company_id (company_id),
    INDEX idx_title (title),
    INDEX idx_location (location),
    INDEX idx_type (type),
    INDEX idx_status (status),
    INDEX idx_application_deadline (application_deadline),
    INDEX idx_is_remote (is_remote),
    INDEX idx_created_at (created_at)
);
