-- Create admin_settings table for dynamic admin system settings
CREATE TABLE IF NOT EXISTS admin_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    platform_name VARCHAR(255) DEFAULT 'Internship Cambodia',
    support_email VARCHAR(255) DEFAULT 'support@internship.kh',
    seo_description TEXT,
    maintenance_mode BOOLEAN DEFAULT FALSE,
    default_language VARCHAR(64) DEFAULT 'English (US)',
    timezone VARCHAR(64) DEFAULT '(GMT+07:00) Phnom Penh',
    brand_logo LONGTEXT NULL,
    brand_favicon LONGTEXT NULL,
    auth_methods JSON,
    brute_force_protection BOOLEAN DEFAULT TRUE,
    ip_whitelist JSON,
    password_min_length INT DEFAULT 8,
    session_timeout_minutes INT DEFAULT 60,
    email_triggers JSON,
    slack_webhook_url TEXT,
    push_notifications BOOLEAN DEFAULT TRUE,
    storage_total_gb DECIMAL(6,2) DEFAULT 100.00,
    storage_used_gb DECIMAL(6,2) DEFAULT 0.00,
    storage_database_gb DECIMAL(6,2) DEFAULT 0.00,
    storage_media_gb DECIMAL(6,2) DEFAULT 0.00,
    storage_logs_gb DECIMAL(6,2) DEFAULT 0.00,
    last_backup_at DATETIME NULL,
    backup_schedule VARCHAR(64) DEFAULT 'Daily at 04:00 AM',
    data_retention_days INT DEFAULT 90,
    last_purge_at DATETIME NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed a default row if none exists
INSERT INTO admin_settings (
    id,
    platform_name,
    support_email,
    seo_description,
    maintenance_mode,
    default_language,
    timezone,
    auth_methods,
    brute_force_protection,
    ip_whitelist,
    password_min_length,
    session_timeout_minutes,
    email_triggers,
    slack_webhook_url,
    push_notifications,
    storage_total_gb,
    storage_used_gb,
    storage_database_gb,
    storage_media_gb,
    storage_logs_gb,
    backup_schedule,
    data_retention_days
) VALUES (
    1,
    'Internship Cambodia',
    'support@internship.kh',
    'The leading platform for finding internships and early career opportunities in Cambodia.',
    FALSE,
    'English (US)',
    '(GMT+07:00) Phnom Penh',
    JSON_OBJECT('Email & Password', TRUE, 'Google OAuth', TRUE, 'Microsoft Azure AD', FALSE),
    TRUE,
    JSON_ARRAY('192.168.1.1', '10.0.0.45'),
    8,
    60,
    JSON_OBJECT(
        'New User Registration', TRUE,
        'Company Verification Request', TRUE,
        'System Error Alerts', TRUE,
        'Weekly Analytics Summary', FALSE
    ),
    '',
    TRUE,
    100.00,
    42.80,
    12.40,
    28.20,
    2.20,
    'Daily at 04:00 AM',
    90
) ON DUPLICATE KEY UPDATE id = id;
