CREATE TABLE IF NOT EXISTS student_verifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  user_id INT NOT NULL,
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  documents TEXT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  rejection_reason TEXT DEFAULT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL,
  reviewed_by INT NULL,
  student_name VARCHAR(255) DEFAULT NULL,
  university VARCHAR(255) DEFAULT NULL,
  major VARCHAR(255) DEFAULT NULL,
  graduation_year INT DEFAULT NULL,
  contact_email VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_student_id (student_id),
  KEY idx_user_id (user_id),
  KEY idx_status (status),
  KEY idx_submitted_at (submitted_at),
  CONSTRAINT fk_student_verifications_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_student_verifications_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_student_verifications_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
